spring:
  application:
    name: customer-loan-service
  datasource:
    url: jdbc:h2:~/temp/test2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8082
logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.search.query: DEBUG
    org.hibernate: INFO





